# Generated by Django 5.2.3 on 2025-07-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('models_pr_unit', models.TextField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.faction')),
            ],
            options={
                'unique_together': {('name', 'faction')},
            },
        ),
        migrations.CreateModel(
            name='UnitStats',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='units.unit')),
                ('movement', models.IntegerField(null=True)),
                ('toughness', models.IntegerField(null=True)),
                ('save', models.IntegerField(null=True)),
                ('wounds', models.IntegerField(null=True)),
                ('leadership', models.IntegerField(null=True)),
                ('objective_control', models.IntegerField(null=True)),
                ('invulnerable_save', models.IntegerField(null=True)),
                ('feel_no_pain', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='units.unit')),
                ('character', models.BooleanField(default=False)),
                ('vehicle', models.BooleanField(default=False)),
                ('infantry', models.BooleanField(default=False)),
                ('monster', models.BooleanField(default=False)),
                ('battleline', models.BooleanField(default=False)),
                ('epic_hero', models.BooleanField(default=False)),
                ('fly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('range', models.IntegerField(null=True)),
                ('range_type', models.TextField(choices=[('melee', 'melee'), ('ranged', 'ranged')])),
                ('attacks', models.IntegerField(null=True)),
                ('ballistic_skill', models.IntegerField(null=True)),
                ('weapon_skill', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
                ('ap', models.IntegerField(null=True)),
                ('damage', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
            options={
                'unique_together': {('unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
            options={
                'unique_together': {('unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UnitKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.keyword')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
            options={
                'unique_together': {('unit', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='WeaponKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.keyword')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.weapon')),
            ],
            options={
                'unique_together': {('weapon', 'keyword')},
            },
        ),
    ]
