version: '3.8'

services:
  db:
    build: ./docker/postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: warhammer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql